### ISSUE TITLE
Add Network Paths as Source for Roms

### ISSUE THREAD

**Issue by ghostyroasty** [ResetCollection/support#44]
As title suggests. I cannot see the mounted network drives when choosing a directory for ROMs.

**Comment by valsou** [comment]
Hi,

I'm looking for this feature before buying the app. ;)

On Shield TV you can map SMB servers (<SMB3) to a mounted folder in /storage. Every app is able to see that folder, i assume Nvidia did the mount "correctly". (I'm not an Android dev, sorry)

On your phone (Android), if you're not rooted, i'm not aware of official ROMs that permit to mount and see network storages as the Shield TV. You can install "Android Samba Client" on F-Droid that will mount a SMB server on a folder in /storage. But the thing is done in a way that only my native file manager (AOSP) is able to see the mounted folder. And no one application (Huawei file manager, DIG front-end, Arc Browser, Retroarch, &c.) can see that folder in their own way of displaying the files.

I hope you'll find a solution. I just saw your tutoriel video, your app is promising.

Cheers,

**Comment by ReCoJav** [comment]
@valsou Hello!

Thanks for all of that info! I've never used network storage on Android devices, so I'm only now learning how to work with these and how to find and used these directories through Android code.

NAS support is the current feature I'm working on. Things have slowed down quite a bit though due to COVID and some challenges my family and I are dealing with right now, but we should be through this by the end of next week. So worst case, NAS support will be in probably like 2 to 3 weeks. Really sorry about this!

As for saving images, you can choose an external storage device for images. Go to the top Settings and you'll see an option to change the image location.

Once I get NAS up and going for ROMs, I'll check for images.

Thanks and take care!

**Comment by ReCoJav** [comment]
@ghostyroasty  and @valsou 
Finally finished this ticket! The new version of RESET that is rolling out now will have mounted network storage support. (v1.0.14)

I only tested this with a Shield TV though. I mounted a NAS by going to Storage > Mount network storage > and I selected my NAS network storage to mount.

Hopefully this is what y'all were looking for! Let me know if otherwise.

Thanks!
